Update severity_test.yml

diff --git a/.github/workflows/severity_test.yml b/.github/workflows/severity_test.yml
--- a/.github/workflows/severity_test.yml
+++ b/.github/workflows/severity_test.yml
@@ -43,3 +43,15 @@ jobs:
           prancer -v
           echo "Run without severity, all should pass.."
           prancer --db NONE severity_none_pass
+          retval=`echo $?`
+          if [ $a -eq 1 ]; then
+            echo "severity_none_pass test case failed..."
+            exit 1
+          fi
+          prancer --db NONE severity_none_fail
+          retval=`echo $?`
+          if [ $a -eq 0 ]; then
+            echo "severity_none_fail test case returned 0..."
+            exit 1
+          fi
+          exit 0
